### ISSUE TITLE
启动后访问报错加载不出页面,这是哪里没有配置好么?

### ISSUE THREAD

**Issue by xhusky** [stkevintan/hexo-theme-material-flow#3]
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: /home/yew/material/themes/material-flow/layout/layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/loading') %>
    4|   <script>setLoadingBarProgress(20)</script> 

/home/yew/material/themes/material-flow/layout/_partial/head.ejs:22
    20|   <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title>
    21|   <meta name="description" content="<%= config.description %>" />
 >> 22|   <meta name="keywords" content="<%=config.keywords.join(',') %>" />
    23|   <meta name="HandheldFriendly" content="True" />
    24|   <meta name="apple-mobile-web-app-capable" content="yes">
    25|   <%- favicon_tag(config.favicon) %>

Cannot read property 'join' of undefined
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:43:388)
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:47:441)
    at /home/yew/material/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiledSync (/home/yew/material/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/yew/material/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/yew/material/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/yew/material/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:927)
    at /home/yew/material/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiled (/home/yew/material/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/yew/material/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/yew/material/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/yew/material/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yew/material/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/yew/material/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/yew/material/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/yew/material/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/yew/material/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/yew/material/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/yew/material/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)

Unhandled rejection TypeError: /home/yew/material/themes/material-flow/layout/layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/loading') %>
    4|   <script>setLoadingBarProgress(20)</script> 

/home/yew/material/themes/material-flow/layout/_partial/head.ejs:22
    20|   <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title>
    21|   <meta name="description" content="<%= config.description %>" />
 >> 22|   <meta name="keywords" content="<%=config.keywords.join(',') %>" />
    23|   <meta name="HandheldFriendly" content="True" />
    24|   <meta name="apple-mobile-web-app-capable" content="yes">
    25|   <%- favicon_tag(config.favicon) %>

Cannot read property 'join' of undefined
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:43:388)
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:47:441)
    at /home/yew/material/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiledSync (/home/yew/material/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/yew/material/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/yew/material/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/yew/material/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at exports.compile (/home/yew/material/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:927)
    at /home/yew/material/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiled (/home/yew/material/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/yew/material/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/yew/material/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/yew/material/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yew/material/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/yew/material/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/yew/material/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/yew/material/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/yew/material/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/yew/material/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/yew/material/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)

**Comment by stkevintan** [comment]
是的，可以详细看看文档中的Settings章节，包括配置文件里面的注释。

**Comment by xhusky** [comment]
@stkevintan  多谢,又重新对了一下 <code>站点配置文件</code>  发现 少了
```
 keywords:
  - A_KEYWORD
  - A_KEYWORD
```
