### ISSUE TITLE
Unhandled rejection TypeError: xx/layout.ejs

### ISSUE THREAD

**Issue by BoilerYao** [stkevintan/hexo-theme-material-flow#8]
Enviroment as follows: (on Ubuntu 16.04)
`hexo: 3.2.2
hexo-cli: 1.0.2
node: 7.4.0
modules: 51
.....
`

Here is the detail of error message:
```
Unhandled rejection TypeError: /home/boiler/blog/themes/material-flow/layout/layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/loading') %>
    4|   <script>setLoadingBarProgress(20)</script> 

/home/boiler/blog/themes/material-flow/layout/_partial/head.ejs:22
    20|   <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title>
    21|   <meta name="description" content="<%= config.description %>" />
 >> 22|   <meta name="keywords" content="<%=config.keywords.join(',') %>" />
    23|   <meta name="HandheldFriendly" content="True" />
    24|   <meta name="apple-mobile-web-app-capable" content="yes">
    25|   <%- favicon_tag(config.favicon) %>

Cannot read property 'join' of undefined
    at eval (eval at exports.compile (/home/boiler/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:43:388)
    at eval (eval at exports.compile (/home/boiler/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:47:1161)
    at /home/boiler/blog/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiledSync (/home/boiler/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/boiler/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/boiler/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/boiler/blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at exports.compile (/home/boiler/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at exports.compile (/home/boiler/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:927)
    at /home/boiler/blog/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiled (/home/boiler/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/boiler/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/boiler/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/boiler/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/boiler/blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/boiler/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/boiler/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/boiler/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/boiler/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/boiler/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/boiler/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)

```

I know little about nodejs and I really like this theme.
( I think it's a package-relate related problem
hoping your reply.

**Comment by stkevintan** [comment]
Thanks, You need add the `keywords` entry into the global `_config.yml` to make things right.

 I'll update the code as soon as possible to make it more robust

**Comment by BoilerYao** [comment]
awesome! thanks for your reply and it works!
