### ISSUE TITLE
hexo s --debug出错

### ISSUE THREAD

**Issue by StyWolf** [stkevintan/hexo-theme-material-flow#9]
Unhandled rejection TypeError: D:\Projects\blog\themes\material-flow\layout\layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/loading') %>
    4|   <script>setLoadingBarProgress(20)</script>

D:\Projects\blog\themes\material-flow\layout\_partial\head.ejs:22
    20|   <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title>
    21|   <meta name="description" content="<%= config.description %>" />
 >> 22|   <meta name="keywords" content="<%=config.keywords.join(',') %>" />
    23|   <meta name="HandheldFriendly" content="True" />
    24|   <meta name="apple-mobile-web-app-capable" content="yes">
    25|   <%- favicon_tag(config.favicon) %>

Cannot read property 'join' of undefined
    at eval (eval at exports.compile (D:\Projects\blog\node_modules\.1.0.0@ejs\lib\ejs.js:242:14), <anonymous>:43:388)
    at eval (eval at exports.compile (D:\Projects\blog\node_modules\.1.0.0@ejs\lib\ejs.js:242:14), <anonymous>:47:1161)
    at D:\Projects\blog\node_modules\.1.0.0@ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (D:\Projects\blog\node_modules\.3.2.2@hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (D:\Projects\blog\node_modules\.3.2.2@hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Projects\blog\node_modules\.3.2.2@hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (D:\Projects\blog\node_modules\.4.17.4@lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (D:\Projects\blog\node_modules\.1.0.0@ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at exports.compile (D:\Projects\blog\node_modules\.1.0.0@ejs\lib\ejs.js:242:14), <anonymous>:30:927)
    at D:\Projects\blog\node_modules\.1.0.0@ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (D:\Projects\blog\node_modules\.3.2.2@hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (D:\Projects\blog\node_modules\.3.2.2@hexo\lib\theme\view.js:29:15)
    at D:\Projects\blog\node_modules\.3.2.2@hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Projects\blog\node_modules\.3.4.7@bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)

**Comment by HuanGong** [comment]
same mistake when i use this theme

**Comment by StyWolf** [comment]
Oh,Sorry.
I forget keywords.
thx
